// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyPic.Contracts.BannedProfiles;

namespace PartyPic.Migrations.BannedProfile
{
    [DbContext(typeof(BannedProfileContext))]
    partial class BannedProfileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PartyPic.Models.BannedProfile.BannedProfile", b =>
                {
                    b.Property<string>("BannedId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BanDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BannedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BannedId");

                    b.ToTable("BannedProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
